DiplomaManagement/Entities/Student.cs
using DiplomaManagement.Data;

namespace DiplomaManagement.Entities
{
    public class Student
    {
        public int Id { get; set; }

        public string StudentUserId { get; set; }

        public virtual ApplicationUser? User { get; set; }

        public virtual ICollection<Enrollment>? Enrollments { get; set; }

        public virtual Thesis? Thesis { get; set; }
        public virtual ThesisProposition? ThesisProposition { get; set; }
    }
}

DiplomaManagement/Controllers/StudentController.cs
using DiplomaManagement.Data;
using DiplomaManagement.Entities;
using DiplomaManagement.Interfaces;
using DiplomaManagement.Models;
using DiplomaManagement.Repositories;
using DiplomaManagement.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace DiplomaManagement.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string? currentFilter, string? searchString, int? page, string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SurnameSortParam = sortOrder == "surname" ? "surname_desc" : "surname";
            ViewBag.EmailSortParam = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.InstituteSortParam = sortOrder == "institute" ? "institute_desc" : "institute";
            ViewBag.ThesisSortParam = sortOrder == "thesis" ? "thesis_desc" : "thesis";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            IQueryable<Student> studentsQuery = _context.Students
                .Include(s => s.User!)
                    .ThenInclude(u => u.Institute)
                .Include(s => s.Thesis);

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();

                studentsQuery = studentsQuery.Where(s =>
                    s.User.FirstName.Contains(searchString) ||
                    s.User.LastName.Contains(searchString) ||
                    s.User.Email.Contains(searchString) ||
                    s.User.Institute.Name.Contains(searchString) ||
                    s.Thesis.Title.Contains(searchString));
            }

            List<Student> students = await studentsQuery.ToListAsync();

            var sortMapping = new Dictionary<string, Func<IEnumerable<Student>, IOrderedEnumerable<Student>>>
            {
                { "name_desc", list => list.OrderByDescending(l => l.User.FirstName) },
                { "surname_desc", list => list.OrderByDescending(l => l.User.LastName) },
                { "surname", list => list.OrderBy(l => l.User.LastName) },
                { "email", list => list.OrderBy(l => l.User.Email) },
                { "email_desc", list => list.OrderByDescending(l => l.User.Email) },
                { "institute", list => list.OrderBy(l => l.User.Institute.Name) },
                { "institute_desc", list => list.OrderByDescending(l => l.User.Institute.Name) },
                { "thesis", list => list.OrderBy(l => l.Thesis?.Title  ?? string.Empty) },
                { "thesis_desc", list => list.OrderByDescending(l => l.Thesis?.Title  ?? string.Empty) }
            };

            if (sortMapping.TryGetValue(sortOrder ?? "", out var sortFunc))
            {
                students = sortFunc(students).ToList();
            }
            else
            {
                students = students.OrderBy(s => s.User.FirstName).ToList();
            }

            int pageSize = 10;
            if (page < 1)
            {
                page = 1;
            }

            int recordsCount = students.Count();
            int pageNumber = page ?? 1;

            PagingService pager = new PagingService(recordsCount, pageNumber, pageSize);
            ViewBag.Pager = pager;

            int itemsToSkip = (pageNumber - 1) * pageSize;

            List<Student> items = students
                .Skip(itemsToSkip)
                .Take(pageSize)
                .ToList();

            return View(items);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> StudentsWithoutThesis(int? page)
        {
            List<Student> students = await _context.Students
                .Include(s => s.User!)
                    .ThenInclude(u => u.Institute)
                .Include(s => s.Enrollments)
                    .ThenInclude(e => e.Thesis)
                .Where(s => s.Thesis == null)
                .ToListAsync();

            int pageSize = 10;
            if (page < 1)
            {
                page = 1;
            }

            int recordsCount = students.Count();
            int pageNumber = page ?? 1;

            PagingService pager = new PagingService(recordsCount, pageNumber, pageSize);
            ViewBag.Pager = pager;

            int itemsToSkip = (pageNumber - 1) * pageSize;

            List<Student> items = students
                .Skip(itemsToSkip)
                .Take(pageSize)
                .ToList();

            return View(items);
        }
    }
}

DiplomaManagement/Controllers/ThesisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DiplomaManagement.Data;
using DiplomaManagement.Entities;
using Microsoft.AspNetCore.Identity;
using DiplomaManagement.Models;
using Microsoft.AspNetCore.Authorization;
using DiplomaManagement.Interfaces;
using DiplomaManagement.Services;
using DiplomaManagement.Resources;
using Microsoft.Extensions.Localization;

namespace DiplomaManagement.Controllers
{
    public class ThesisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _env;
        private readonly IConfiguration _configuration;
        private readonly INotificationService _notificationService;
        private readonly IThesisRepository _thesisRepository;
        private readonly IStringLocalizer<SharedResource> _htmlLocalizer;

        public ThesisController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment env, IConfiguration configuration, INotificationService notificationService, IThesisRepository thesisRepository, IStringLocalizer<SharedResource> htmlLocalizer)
        {
            _context = context;
            _userManager = userManager;
            _env = env;
            _configuration = configuration;
            _notificationService = notificationService;
            _thesisRepository = thesisRepository;
            _htmlLocalizer = htmlLocalizer;
        }

        // GET: Thesis
        [Authorize(Roles = "Promoter")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound("User not found.");
            }

            Promoter? promoter = await _context.Promoters
                .Include(p => p.Theses!)
                    .ThenInclude(t => t.PdfFiles.Where(p => p.PdfType == PdfType.example))
                .Include(p => p.Theses!)
                    .ThenInclude(t => t.PresentationFile)
                .FirstOrDefaultAsync(p => p.PromoterUserId == user.Id);

            if(promoter != null) 
            {
                if (promoter.Theses == null)
                    return View(new List<Thesis>());
                else
                    return View(promoter.Theses);
            }
            else 
                return NotFound();
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> AvailableTheses(string? currentFilter, string? searchString, int? page, string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParam = string.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.DescriptionSortParam = sortOrder == "description" ? "description_desc" : "description";
            ViewBag.PromoterSortParam = sortOrder == "promoter" ? "promoter_desc" : "promoter";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            ApplicationUser? user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound("User not found.");
            }

            Student? student = await _context.Students
                .Include(s => s.Thesis)
                .FirstOrDefaultAsync(p => p.StudentUserId == user.Id);

            if (student == null)
            {
                return NotFound("Student not found.");
            }

            if (student.Thesis != null)
            {
                ViewBag.Thesis = student.Thesis;
            }

            IQueryable<Thesis> thesesQuery = _context.Theses
                .Include(t => t.Promoter!)
                    .ThenInclude(p => p.User)
                .Include(t => t.Enrollments)
                .Where(t => t.Promoter!.User!.InstituteId == user.InstituteId && t.StudentId == null && !t.Enrollments!.Any(u => u.StudentId == student.Id));

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();

                thesesQuery = thesesQuery.Where(t =>
                    t.Title.Contains(searchString) ||
                    t.Description.Contains(searchString) ||
                    t.Promoter.User.FirstName.Contains(searchString) ||
                    t.Promoter.User.LastName.Contains(searchString));
            }

            List<Thesis> theses = await thesesQuery.ToListAsync();

            var sortMapping = new Dictionary<string, Func<IEnumerable<Thesis>, IOrderedEnumerable<Thesis>>>
            {
                { "title_desc", theses => theses.OrderByDescending(t => t.Title) },
                { "description_desc", theses => theses.OrderByDescending(t => t.Description) },
                { "description", theses => theses.OrderBy(t => t.Description) },
                { "promoter", theses => theses.OrderBy(t => t.Promoter.User.FirstName) },
                { "promoter_desc", theses => theses.OrderByDescending(t => t.Promoter.User.FirstName) }
            };

            if (sortMapping.TryGetValue(sortOrder ?? "", out var sortFunc))
            {
                theses = sortFunc(theses).ToList();
            }
            else
            {
                theses = theses.OrderBy(t => t.Title).ToList();
            }

            int pageSize = 10;
            if (page < 1)
            {
                page = 1;
            }

            int recordsCount = theses.Count();
            int pageNumber = page ?? 1;

            PagingService pager = new PagingService(recordsCount, pageNumber, pageSize);
            ViewBag.Pager = pager;

            int itemsToSkip = (pageNumber - 1) * pageSize;

            List<Thesis> items = theses
                .Skip(itemsToSkip)
                .Take(pageSize)
                .ToList();

            return View(items);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminAvailableTheses(int studentId)
        {
            Student? student = await _context.Students
                .Include(s => s.User)
                .Include(s => s.Enrollments!)
                    .ThenInclude(e => e.Thesis)
                        .ThenInclude(t => t.Promoter)
                            .ThenInclude(p => p.User)
                .FirstOrDefaultAsync(p => p.Id == studentId);

            if (student != null)
            {
                List<int> thesisIds = student.Enrollments
                    .Where(e => e.Thesis != null)
                    .Select(e => e.Thesis!.Id)
                    .ToList();

                List<Thesis> theses = await _context.Theses
                    .Include(t => t.Promoter!)
                        .ThenInclude(p => p.User)
                    .Where(t => t.StudentId == null && t.Promoter!.User!.InstituteId == student.User!.InstituteId && !thesisIds.Contains(t.Id))
                    .ToListAsync();

                if (student.Enrollments.Any())
                {
                    ViewBag.Enrollments = student.Enrollments;
                }

                ViewBag.SelectedStudentId = studentId;

                return View(theses);
            }
            else
            {
                return NotFound("Student not found.");
            }
        }

        [Authorize(Roles = "Promoter")]
        public async Task<IActionResult> ActiveTheses()
        {
            ApplicationUser? user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                List<Thesis> theses = await _context.Theses
                    .Include(t => t.Student!)
                        .ThenInclude(p => p.User)
                    .Where(t => t.Promoter!.User!.Id == user.Id && t.StudentId != null)
                    .ToListAsync();

                return View(theses);
            }
            else 
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "SeminarLeader")]
        public async Task<IActionResult> SeminarLeaderTheses(string? currentFilter, string? searchString, int? page, string sortOrder = "")
        {
            ApplicationUser? user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.TitleSortParam = string.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
                ViewBag.StudentSortParam = sortOrder =="student" ? "student_desc" : "student";
                ViewBag.PromoterSortParam = sortOrder == "promoter" ? "promoter_desc" : "promoter";
                ViewBag.StatusSortParam = sortOrder == "status" ? "status_desc" : "status";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;


                IQueryable<Thesis> thesesQuery = _context.Theses
                    .Include(t => t.Student!)
                        .ThenInclude(s => s.User)
                    .Include(t => t.Promoter!)
                        .ThenInclude(p => p.User)
                    .Where(t => t.Promoter!.User!.InstituteId == user.InstituteId);

                bool isEnum = Enum.TryParse<ThesisStatus>(searchString, true, out var statusEnum);

                if (!string.IsNullOrEmpty(searchString))
                {
                    searchString = searchString.ToLower();
                    
                    thesesQuery = thesesQuery.Where(t =>
                        t.Title.Contains(searchString) ||

DiplomaManagement/Views/Student/Index.cshtml
@using DiplomaManagement.Services;
@using DiplomaManagement.Interfaces

@model IEnumerable<DiplomaManagement.Entities.Student>

@{
    ViewData["Title"] = "Index";

    PagingService pager = new PagingService();
    int pageNumber = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNumber = pager.CurrentPage;
    }

    PagerViewModel pagerViewModel = new PagerViewModel
    {
        Pager = pager,
        ControllerName = "Student",
        ActionName = "Index"
    };
}

<h1>@Localizer["list-of-all-students"]</h1>

@if (Model != null && Model.Any())
{
    <form asp-action="Index" method="get">
        <div class="form-actions no-color">
            <p>
                @Localizer["search-by-phrase"] <input type="text" name="searchString" value="@ViewBag.CurrentFilter" />
                <input type="submit" value="@Localizer["search"]" class="btn btn-outline-light" /> |
                <a asp-action="Index" class="btn btn-outline-light">@Localizer["back-to-full-list"]</a>
            </p>
        </div>
    </form>

    <div class="table-wrapper mb-3">
        <table class="table table-hover data-table mb-0">
            <thead>
                <tr>
                    <th>
                        <a class="pb-1 table-filter @(string.IsNullOrEmpty(ViewBag.CurrentSort) ? "active" : "")"
                            asp-action="Index" 
                            asp-route-sortOrder="@ViewBag.NameSortParam" 
                            asp-route-currentFilter="@ViewBag.currentFilter">
                            @Localizer["first-name"]
                        </a>
                    </th>
                    <th>
                        <a class="pb-1 table-filter @(ViewBag.CurrentSort == "surname" ? "active" : "")"
                            asp-action="Index" 
                            asp-route-sortOrder="@ViewBag.SurnameSortParam" 
                            asp-route-currentFilter="@ViewBag.currentFilter">
                            @Localizer["last-name"]
                        </a>
                    </th>
                    <th>
                        <a class="pb-1 table-filter @(ViewBag.CurrentSort == "email" ? "active" : "")"
                            asp-action="Index" 
                            asp-route-sortOrder="@ViewBag.EmailSortParam" 
                            asp-route-currentFilter="@ViewBag.currentFilter">
                            @Localizer["email-address"]
                        </a>
                    </th>
                    <th>
                        <a class="pb-1 table-filter @(ViewBag.CurrentSort == "institute" ? "active" : "")"
                            asp-action="Index" 
                            asp-route-sortOrder="@ViewBag.InstituteSortParam" 
                            asp-route-currentFilter="@ViewBag.currentFilter">
                            @Localizer["institute"]
                        </a>
                    </th>
                    <th>
                        <a class="pb-1 table-filter @(ViewBag.CurrentSort == "thesis" ? "active" : "")"
                            asp-action="Index" 
                            asp-route-sortOrder="@ViewBag.ThesisSortParam" 
                            asp-route-currentFilter="@ViewBag.currentFilter">
                            @Localizer["thesis-title"]
                        </a>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Institute.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Thesis.Title)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id">@Localizer["details-button"]</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <partial name="Icons/_WarningIconPartial" />
        <div>
            @Localizer["no-students-in-institute"]
        </div>
    </div>
}

<partial name="_PagerPartial" model="@pagerViewModel" />

DiplomaManagement/Views/Student/StudentsWithoutThesis.cshtml
@using DiplomaManagement.Services;
@using DiplomaManagement.Interfaces

@model IEnumerable<DiplomaManagement.Entities.Student>
@inject INotificationService NotificationService

@{
    ViewData["Title"] = "Index";
    var notificationMessage = NotificationService.GetNotification($"SuccessfullAssigned_{User.Identity.Name}");

    PagingService pager = new PagingService();
    int pageNumber = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNumber = pager.CurrentPage;
    }

    PagerViewModel pagerViewModel = new PagerViewModel
    {
        Pager = pager,
        ControllerName = "Student",
        ActionName = "Index"
    };
}

@if (!string.IsNullOrEmpty(notificationMessage))
{
    var toastModel = new DiplomaManagement.Models.ToastNotificationViewModel
    {
        Title = "Success",
        Message = notificationMessage,
        Class = "bg-success"
    };

    @section ToastNotification {
        @await Html.PartialAsync("_ToastNotificationPartial", toastModel)
    }
}

<h1>@Localizer["list-of-students-without-thesis"]</h1>

@if (Model != null && Model.Any())
{
    <form asp-controller="Thesis" asp-action="AssignThesisToStudents" method="post" id="studentsForm">
        <button type="button" class="btn btn-primary" onclick="checkSelection()">@Localizer["submit-selected"]</button>

        <div class="table-wrapper mb-3">
            <table class="table table-hover data-table mb-0">
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" id="select-all" />
                        </th>
                        <th>
                            <a class="pb-1 table-filter @(string.IsNullOrEmpty(ViewBag.CurrentSort) ? "active" : "")"
                                asp-action="Index" 
                                asp-route-sortOrder="@ViewBag.NameSortParam" 
                                asp-route-currentFilter="@ViewBag.currentFilter">
                                @Localizer["first-name"]
                            </a>
                        </th>
                        <th>
                            <a class="pb-1 table-filter @(ViewBag.CurrentSort == "surname" ? "active" : "")"
                                asp-action="Index" 
                                asp-route-sortOrder="@ViewBag.SurnameSortParam" 
                                asp-route-currentFilter="@ViewBag.currentFilter">
                                @Localizer["last-name"]
                            </a>
                        </th>
                        <th>
                            <a class="pb-1 table-filter @(ViewBag.CurrentSort == "email" ? "active" : "")"
                                asp-action="Index" 
                                asp-route-sortOrder="@ViewBag.EmailSortParam" 
                                asp-route-currentFilter="@ViewBag.currentFilter">
                                @Localizer["email-address"]
                            </a>
                        </th>
                        <th>
                            <a class="pb-1 table-filter @(ViewBag.CurrentSort == "institute" ? "active" : "")"
                                asp-action="Index" 
                                asp-route-sortOrder="@ViewBag.InstituteSortParam" 
                                asp-route-currentFilter="@ViewBag.currentFilter">
                                @Localizer["institute"]
                            </a>
                        </th>
                        <th>
                            @Localizer["student-enrollments"]
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="selectedStudents" value="@item.Id" class="student-checkbox" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Institute.Name)
                            </td>
                            <td>
                                @if (item.Enrollments != null && item.Enrollments.Any())
                                {
                                    <ul>
                                        @foreach (var enrollment in item.Enrollments)
                                        {
                                            <li>@enrollment.Thesis.Title</li>
                                        }
                                    </ul>
                                }
                                else
                                {
                                    <span>--</span>
                                }
                            </td>
                            <td>
                                <a asp-controller="Thesis" asp-action="AdminAvailableTheses" asp-route-studentId="@item.Id" class="btn btn-primary">@Localizer["assign-thesis-manually"]</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </form>

    <partial name="_PagerPartial" model="@pagerViewModel" />
}
else
{
    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <partial name="Icons/_WarningIconPartial" />
        <div>
            @Localizer["no-students-without-thesis"]
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="noSelectionModal" tabindex="-1" aria-labelledby="noSelectionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="noSelectionModalLabel">No Students Selected</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Please select at least one student to proceed.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('select-all').addEventListener('click', function() {
        var checkboxes = document.querySelectorAll('.student-checkbox');
        for (var checkbox of checkboxes) {
            checkbox.checked = this.checked;
        }
    });

    function checkSelection() {
        var checkboxes = document.querySelectorAll('.student-checkbox:checked');
        console.log(checkboxes);
        if (checkboxes.length === 0) {
            var modal = new bootstrap.Modal(document.getElementById('noSelectionModal'));
            modal.show();
        } else {
            document.getElementById('studentsForm').submit();
        }
    }
</script>