DiplomaManagement/Entities/Enrollment.cs
namespace DiplomaManagement.Entities
{
    public class Enrollment
    {
        public int Id { get; set; }

        public int ThesisId { get; set; }

        public virtual Thesis? Thesis { get; set; }

        public int StudentId { get; set; }

        public virtual Student? Student { get; set; }

    }
}

DiplomaManagement/Controllers/EnrollmentController.cs
using DiplomaManagement.Data;
using DiplomaManagement.Entities;
using DiplomaManagement.Interfaces;
using DiplomaManagement.Resources;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace DiplomaManagement.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotificationService _notificationService;
        private readonly IThesisRepository _thesisRepository;
        private readonly IStringLocalizer<SharedResource> _htmlLocalizer;

        public EnrollmentController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, INotificationService notificationService, IThesisRepository thesisRepository, IStringLocalizer<SharedResource> htmlLocalizer)
        {
            _context = context;
            _userManager = userManager;
            _notificationService = notificationService;
            _thesisRepository = thesisRepository;
            _htmlLocalizer = htmlLocalizer;
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> Create(int thesisId)
        {
            var user = await _userManager.GetUserAsync(User);

            var student = await _context.Students
            .FirstOrDefaultAsync(p => p.StudentUserId == user.Id);

            if (student != null) 
            {
                var createdEnrollment = await _context.Enrollments
                    .Where(e => e.ThesisId == thesisId && e.StudentId == student.Id)
                    .AnyAsync();

                if (createdEnrollment)
                {
                    _notificationService.AddNotification($"EnrollmentCreationError_{User.Identity.Name}", _htmlLocalizer["already-created-enrollment"]);
                }
                else
                {
                    Thesis? thesis = await _context.Theses.FirstOrDefaultAsync(t => t.Id == thesisId);
                    
                    if (thesis == null)
                    {
                        return NotFound();
                    }

                    thesis.Status = ThesisStatus.Requested;

                    Enrollment enrollment = new Enrollment
                    {
                        ThesisId = thesisId,
                        StudentId = student.Id
                    };

                    await _context.AddAsync(enrollment);
                    await _context.SaveChangesAsync();
                    _notificationService.AddNotification($"EnrollmentCreated_{User.Identity.Name}", _htmlLocalizer["enrollment-created-success"]);
                }
            }

            return RedirectToAction("AvailableTheses", "Thesis");
        }

        [Authorize(Roles = "Promoter")]
        public async Task<IActionResult> ActiveEnrollments()
        {
            var user = await _userManager.GetUserAsync(User);

            var enrollments = await _context.Enrollments
                .Include(e => e.Thesis)
                    .ThenInclude(t => t.Promoter)
                .Include(e => e.Student)
                    .ThenInclude(s => s.User)
                .Where(e => e.Thesis.Promoter.PromoterUserId == user.Id)
                .ToListAsync();

            return View(enrollments);
        }

        [Authorize(Roles = "Promoter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitEnrollment(int id)
        {
            Enrollment? enrollment = await _context.Enrollments
                .Include(e => e.Thesis)
                    .ThenInclude(t => t.Enrollments)
                .FirstOrDefaultAsync(e => e.Id == id);

            if (enrollment != null)
            {
                List<Enrollment> thesisEnrollments = await _context.Enrollments
                    .Where(e => e.StudentId == enrollment.StudentId && e.ThesisId != enrollment.ThesisId)
                    .ToListAsync();

                thesisEnrollments.AddRange(enrollment.Thesis.Enrollments);

                await _thesisRepository.assignThesisToStudent(enrollment.Thesis, enrollment.StudentId, thesisEnrollments);

                _notificationService.AddNotification($"SuccessfullAssigned_{User.Identity.Name}", _htmlLocalizer["assign-selected-student-success"]);
            }

            return RedirectToAction("ActiveEnrollments");
        }
    }
}

DiplomaManagement/Views/Enrollment/ActiveEnrollments.cshtml
@using DiplomaManagement.Interfaces
@model IEnumerable<DiplomaManagement.Entities.Enrollment>

@inject INotificationService NotificationService

@{
    ViewData["Title"] = @Localizer["active-enrollments"];
    var successMessage = NotificationService.GetNotification($"SuccessfullAssigned_{User.Identity.Name}");
}

@if (!string.IsNullOrEmpty(successMessage))
{
    var toastModel = new DiplomaManagement.Models.ToastNotificationViewModel
    {
        Title = "Success",
        Message = successMessage,
        Class = "bg-success"
    };

    @section ToastNotification {
        @await Html.PartialAsync("_ToastNotificationPartial", toastModel)
    }
}

<h1>@Localizer["active-enrollments"]</h1>

@if (Model != null && Model.Any())
{
    <div class="table-wrapper mb-3">
        <table class="table table-hover data-table mb-0">
            <thead>
                <tr>
                    <th>
                        @Localizer["thesis-title"]
                    </th>
                    <th>
                        @Localizer["student-name-surname"]
                    </th>
                    <th>
                        @Localizer["student-email"]
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Thesis.Title)
                        </td>
                        <td>
                            @($"{item.Student.User.FirstName} {item.Student.User.LastName}")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.User.Email)
                        </td>
                        <td>
                            <button class="btn btn-primary btn-submit" data-bs-toggle="modal" data-bs-target="#confirmationModal" data-id="@item.Id">@Localizer["submit"]</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <partial name="Icons/_WarningIconPartial" />
        <div>
            @Localizer["no-active-enrollments"]
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">@Localizer["confirm-action"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Localizer["aus-submit-enrollment"]
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["cancel"]</button>
                <button type="button" class="btn btn-primary" id="confirmSubmit">@Localizer["submit"]</button>
            </div>
        </div>
    </div>
</div>
<form id="hiddenForm" method="post" style="display:none;"></form>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var submitButtons = document.querySelectorAll('.btn-submit');
            var confirmButton = document.getElementById('confirmSubmit');
            var currentItemId;

            submitButtons.forEach(function (button) {
                button.addEventListener('click', function () {
                    currentItemId = this.getAttribute('data-id');
                });
            });

            confirmButton.addEventListener('click', function () {
                var form = document.getElementById('hiddenForm');
                form.action = '@Url.Action("SubmitEnrollment", "Enrollment")/' + currentItemId;
                form.submit();
            });
        });
    </script>
}